[package]
name = "rust_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
futures = "0.3"
futures-util = "0.3"
git2 = "0.20"
globset = "0.4"
hound = "3.4"
hyper-util = "0.1.16"
log = "0.4"
os_pipe = "1.2"
rand = "0.9"
ratatui = "0.28.0"
regex = "1.10"
reqwest = { version = "0.12", features = ["json", "blocking", "stream"] }
rodio = "0.21"
rpassword = "7.4"
axum = { version = "0.8", features = ["macros"] }
rmcp = { version = "0.11", features = [
  "server",
  "transport-io",
  "macros",
  "client",
  "transport-io",
  "transport-streamable-http-server",
  "auth",
  "elicitation",
  "schemars",
] }
schemars = "1.0"
scopeguard = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ssh_cfg = "0.3"
tempdir = "0.3"
tempfile = "3.21"
tokio = { version = "1.44", features = ["full"] }
tokio-util = { version = "0.7" }
tokio-native-tls = "0.3.1"
tokio-stream = { version = "0.1", features = ["sync"] }
tracing-subscriber = { version = "0.3", features = ["fmt", "std", "env-filter"] }
tracing = "0.1"
toml = "0.8"
url = "2.5"
walkdir = "2"
